name: habit_tracker
description: "A habit tracking app with Firebase integration and motivational quotes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.3.1
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # UI and utilities
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  fl_chart: ^0.66.0
  
  # HTTP for quotes API
  http: ^1.1.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
