// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEEaLA5GzqGQtKOg_WyM07rmlCDZcTk6w',
    appId: '1:1046474576175:web:994eccbfb134115b9d11da',
    messagingSenderId: '1046474576175',
    projectId: 'habit-tracker-app-92ea5',
    authDomain: 'habit-tracker-app-92ea5.firebaseapp.com',
    storageBucket: 'habit-tracker-app-92ea5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTVs0U5w4gTShC4KpQM_ncf9_fF1OuTd8',
    appId: '1:1046474576175:android:7d440f2937bab2dd9d11da',
    messagingSenderId: '1046474576175',
    projectId: 'habit-tracker-app-92ea5',
    storageBucket: 'habit-tracker-app-92ea5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXlpBtSJckHap1gsvQHT_s3yUWsNJ7o0M',
    appId: '1:1046474576175:ios:6581406c114de7a69d11da',
    messagingSenderId: '1046474576175',
    projectId: 'habit-tracker-app-92ea5',
    storageBucket: 'habit-tracker-app-92ea5.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXlpBtSJckHap1gsvQHT_s3yUWsNJ7o0M',
    appId: '1:1046474576175:ios:6581406c114de7a69d11da',
    messagingSenderId: '1046474576175',
    projectId: 'habit-tracker-app-92ea5',
    storageBucket: 'habit-tracker-app-92ea5.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEEaLA5GzqGQtKOg_WyM07rmlCDZcTk6w',
    appId: '1:1046474576175:web:96f4ec29efb5a5859d11da',
    messagingSenderId: '1046474576175',
    projectId: 'habit-tracker-app-92ea5',
    authDomain: 'habit-tracker-app-92ea5.firebaseapp.com',
    storageBucket: 'habit-tracker-app-92ea5.firebasestorage.app',
  );
}
